### ISSUE TITLE
NDI connect Error code 257

### ISSUE THREAD

**Issue by Mixmorks** [SciKit-Surgery/scikit-surgerynditracker#55]
I am trying to run scikit's surgerynditracker on a Windows 11 machine with Python 3.8.10, but the code fails when calling ndicapi's ndiProbe function:
![image](https://user-images.githubusercontent.com/6385016/184019519-9d0a0993-768b-4307-8144-f8794ea24fbd.png)
The console output is this:
```
Probing port:  0  got name:  COM19  Result:  257
Traceback (most recent call last):
  File "c:/Users/User/Documents/GitHub/AR_Snake_3.0/TcpClient.py", line 16, in <module>
    TRACKER = NDITracker(SETTINGS)
  File "C:\Users\User\AppData\Roaming\Python\Python38\site-packages\sksurgerynditracker\nditracker.py", line 138, in __init__
    self._connect_polaris(configuration)
  File "C:\Users\User\AppData\Roaming\Python\Python38\site-packages\sksurgerynditracker\nditracker.py", line 187, in _connect_polaris
    name = _get_serial_port_name(configuration)
  File "C:\Users\User\AppData\Roaming\Python\Python38\site-packages\sksurgerynditracker\nditracker.py", line 79, in _get_serial_port_name
    raise IOError(
OSError: Could not find any NDI device in 1 serial port candidates checked. Please check the following:
        1) Is an NDI device connected to your computer?
        2) Is the NDI device switched on?
        3) Do you have sufficient privilege to connect to the device? (e.g. on Linux are you part of the "dialout" group?)
```
The answer to the last three questions is: "Yes", "Yes" and "I think I do".
I have installed the NDI drivers following the NDI Toolbox. Release 5.002.022. The camera is showing up in my Device Driver as COM19:
![image](https://user-images.githubusercontent.com/6385016/184018728-99cddd5b-0e11-4e77-ac21-25093cbfdb19.png)

I am able to connect to the port using either Putty or the Python Serial library so I do think I have access to this port. I can also connect to the port using the NDI Track tool:
![image](https://user-images.githubusercontent.com/6385016/184020717-0629b980-964b-4169-b49d-ed904e276c84.png)

I have tried running this code from Visual Studio Code and the CMD terminal, both as a regular user and as Administrator. Everytime, same message.

Any ideas on what else I might be able to try?

Much appreciated!

**Comment by Mixmorks** [comment]
I closed the toolbox for these trials but now I wonder if there is a way to find out if something else is already using that port.
I ran:
`from serial.tools import list_ports
list_ports.comports()`

and it returned an empty string. I disabled and re-enabled the port in hopes that it might kick out whatever else tries to use it but that didn't fix it either unfortunately. I will try reinstalling the drivers.

**Comment by thompson318** [comment]
OK, thanks for the update. The fact that list_ports doesn't work suggests it's a problem beyond the scope of ndicapi. I'm on holiday for a couple of weeks now so can't offer much more support for now, sorry. I'll see how you got on when I return. In the meantime I'd suggest looking through the issues at [https://github.com/pyserial/pyserial](https://github.com/pyserial/pyserial), there might be something related.

**Comment by Mixmorks** [comment]
No worries. I appreciate the help. Enjoy your break.
I will keep looking into it and post the solution here when I find it in case someone has this issue in the future.

**Comment by Mixmorks** [comment]
One thing to note for posterity, according to a comment underneath [this stackoverflow question](https://stackoverflow.com/questions/12090503/listing-available-com-ports-with-python), `list_ports.comports()` was buggy at some point. They recommend using `print([comport.device for comport in serial.tools.list_ports.comports()])`. 
When I do that the ports show up as expected so `list_ports.comports()` might still have issues.

**Comment by Mixmorks** [comment]
I have found the root of the problem:
1. ndicapi uses the Windows CreateFile function [(see line 67)](https://github.com/PlusToolkit/ndicapi/blob/93a71e2a66cebecd9555a446f7e066b8cb68031a/ndicapi_serial_win32.cxx)
2. Windows has reserved file names for system interfaces, including the COM ports.
3. However, they have only reserved COM1-COM9 ([see Naming Conventions](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file))
4. COM ports with numbers larger than 9 need a specific pre-amble. The [example they give](https://support.microsoft.com/en-us/topic/howto-specify-serial-ports-larger-than-com9-db9078a5-b7b6-bf00-240f-f749ebfd913e) is
`CreateFile("\\\\.\\COM10" [...]`

My laptop defaults to COM port 21 (I don't know why that is but it is what it is). Hence when I try to call CreateFile it returns error code 2 which is [File Not Found](https://docs.microsoft.com/en-us/windows/win32/debug/system-error-codes--0-499-).

**Comment by Mixmorks** [comment]
Closing the issue and will suggest a fix to ndicapi.

**Comment by thompson318** [comment]
This is slightly complicated by ndicapi issues https://github.com/PlusToolkit/ndicapi/issues/34 and https://github.com/PlusToolkit/ndicapi/issues/24. We can fix it by reverting to using ndiDeviceName or doing something with PySerial

**Comment by rajkundu** [comment]
Hi! I filed https://github.com/PlusToolkit/ndicapi/issues/34 (sorry for duplicating https://github.com/PlusToolkit/ndicapi/issues/24!) and fixed it with https://github.com/PlusToolkit/ndicapi/pull/35. I saw this issue and am happy to help however I can. That being said, I'm a bit confused and just want to make sure I understand what's going on. My understanding is as follows:

- Due to the 4-port macOS bug in `ndicapi`, `scikit-surgerynditracker` began using `pySerial` rather than `ndiGetSerialDeviceName` for NDI device discovery.
- Windows has some weird COM port >10 behavior which causes issues with this library's current `pySerial` implementation.
- `ndicapi` has been fixed and now both supports >10 COM ports on Windows as well as >4 ports on macOS.

So you have to decide whether to a) revert to using `ndicapi`, or b) stick with the current `pySerial` implementation and account for >10 COM ports manually. Is this correct?

**Comment by thompson318** [comment]
> So you have to decide whether to a) revert to using `ndicapi`, or b) stick with the current `pySerial` implementation and account for >10 COM ports manually. Is this correct?

Yes, that basically covers it. Logically it might make most sense to revert to using ndiGetSerialDeviceName now, however I'd quite like to keep using pyserial. I think it may be better at discovering serial ports than ndiGetSerialDeviceName which just runs through the first n ports. So I've just pushed branch https://github.com/SciKit-Surgery/scikit-surgerynditracker/tree/55-com-greater-than-9. If you're able to test it on your hardware that would be great. Thanks.

**Comment by rajkundu** [comment]
Unfortunately, I may not be able to test it for a little while as my primary computer is a Mac. Hopefully someone else can test it in the meantime?

In any case, I agree. I think using pySerial is good for a number of reasons, especially because doing so makes it easy to extend functionality in the future if desired. Also, all `ndiGetSerialDeviceName` does at the end of the day is manually check and adjust for COM > 10 – so no reason you can't do that yourself!

**Comment by rajkundu** [comment]
I finally got around to testing on a Windows computer (sorry for the extraordinarily long delay), but now I'm having an issue where the NDI camera doesn't show up at all. On my Mac, I can see it listed when I run the command `ls /dev/cu.*`, but I don't see it listed as a COM port in the Windows device manager. Instead, it shows up as an unknown device called "NDI Host USB Converter."

Am I missing something? I cloned this repository, installed its requirements using `pip install -r requirements.txt`, and attached the Polaris to my Windows laptop via a USB B-to-USB A cable. Still, it doesn't show up as a COM port. What is the usual process for connecting a Polaris camera to a Windows machine?

**Comment by thompson318** [comment]
I think on Windows you might need a driver installation. Has the windows machine you're using got any NDI software on it already?

**Comment by rajkundu** [comment]
The computer I'm using does not have any NDI software, but I think I have an NDI account and can download drivers from there. Once I do that, I'll let you know how testing goes. Thank you!

**Comment by rajkundu** [comment]
I installed the driver, and the NDI camera shows up as a COM port (e.g., COM3), but I'm now having an issue with opening the device. While NDI's own Track.exe program works fine, my simple C++ program which uses [PlusToolkit/ndicapi](https://github.com/PlusToolkit/ndicapi) can't find the camera because it fails to open the COM port. I'm probing ports 1-20 but getting NDI Error 257 on all of them.

I think the error originates in the [`ndiSerialOpen`](https://github.com/PlusToolkit/ndicapi/blob/93a71e2a66cebecd9555a446f7e066b8cb68031a/ndicapi_serial_win32.cxx#L67) function. I'm using a company laptop, so it could be a permissions error or something similar. In any case, I'll try some more detailed debugging next week. Hopefully, once I get COM ports <= 10 to work, I can test those > 10 and test Python as well.

**Comment by rajkundu** [comment]
My C++ error ended up being a bug in my own async code, not a permissions error. After fixing it, I tested the `55-com-greater-than-9` branch of this repository. In order to test COM ports > 9, I manually assigned the NDI device to `COM13` through Windows Device Manager.

Here is the test script I ran, `test.py`:
```python
import time
from sksurgerynditracker.nditracker import NDITracker
import numpy as np

settings_polaris = {
    "tracker type": "polaris",
    "romfiles": ["data/8700339.rom"]
}
tracker = NDITracker(settings_polaris)
print(f"Device info: {tracker._device}")

tracker.start_tracking()
tracker.get_tool_descriptions()
print("Successfully started tracking")

try:
    while(True):
        port_numbers, time_stamps, frame_numbers, tracking, tracking_quality = tracker.get_frame()
        time.sleep(0.05)
except KeyboardInterrupt:
    pass

tracker.stop_tracking()
tracker.close()
print("Finished cleanup")
```

And here is its output:
```
(tms_base) C:\Users\rk274\code\scikit-surgerynditracker>python test.py
Device info: <polaris object 0000029055E98D40, \\.\COM13>
Successfully started tracking
Finished cleanup
```

So, I'm happy to say that COM ports > 9 (and <= 9) work, at least on my Windows 11 machine!

**Comment by thompson318** [comment]
That's great, thank you for testing it. I will merge and close the issue.
